[package]
name = "basic"
version = "0.1.0"
edition = "2024"

[dependencies]
foxtive-supervisor = { path = "../../" }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "time", "macros"] }
async-trait = "0.1.89"
anyhow = "1.0.100"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
