name: Code QA & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test-code:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Run Tests
        run: cargo test --workspace --features=regex,crypto,base64,hmac,reqwest,multipart

      - name: Run cargo fmt
        if: github.event_name == 'push'
        run: cargo fmt --all

      - name: Commit fmt changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(cargo-fmt): apply changes" || echo "No changes to commit"

      - name: Push fmt changes
        if: github.event_name == 'push' && success()
        run: git push origin HEAD:${{ github.ref }}

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: test-code
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Detect changes in crates and release updated crates
        run: |
          # Check if foxtive has changed
          if git diff --quiet HEAD~1..HEAD -- foxtive/; then
            echo "No changes in foxtive"
          else
            echo "Changes detected in foxtive, publishing..."
            cargo publish -p foxtive
          fi
          
          # Check if foxtive-macros has changed
          if git diff --quiet HEAD~1..HEAD -- foxtive-macros/; then
            echo "No changes in foxtive-macros"
          else
            echo "Changes detected in foxtive-macros, publishing..."
            cargo publish -p foxtive-macros
          fi

  lint-code:
    name: Lint Codebase
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        if: github.event_name == 'push'
        run: cargo fmt --all

      - name: Commit fmt changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(cargo-fmt): apply changes" || echo "No changes to commit"

      - name: Push fmt changes
        if: github.event_name == 'push' && success()
        run: git push origin HEAD:${{ github.ref }}
