name: Code QA & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  detect-changes:
    name: Detect Changed Crates
    runs-on: ubuntu-latest

    outputs:
      changed_crates: ${{ steps.detect-changes.outputs.changed_crates }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Detect changed crates
        id: detect-changes
        run: |
          # Check if HEAD~1 exists
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            CHANGED_CRATES=$(git diff --name-only HEAD~1..HEAD | grep -E '^[^/]+/' | cut -d '/' -f 1 | sort | uniq)
          else
            # If HEAD~1 does not exist, assume all crates are changed (e.g., first commit)
            CHANGED_CRATES=$(find . -maxdepth 1 -type d -not -path './.*' -not -path '.' | cut -d '/' -f 2 | sort | uniq)
          fi
          echo "Changed crates: $CHANGED_CRATES"
          echo "::set-output name=changed_crates::$CHANGED_CRATES"

  test-code:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: detect-changes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Run Clippy on changed crates
        run: |
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive"* ]]; then
            cargo clippy --package foxtive --all-targets --all-features
          fi
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive-macros"* ]]; then
            cargo clippy --package foxtive-macros --all-targets --all-features
          fi

      - name: Run Tests on changed crates
        run: |
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive"* ]]; then
            cargo test --package foxtive --features=regex,crypto,base64,hmac,reqwest
          fi
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive-macros"* ]]; then
            cargo test --package foxtive-macros --features=database
          fi

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: [detect-changes, test-code]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Detect changes in crates and release updated crates
        run: |
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive"* ]]; then
            echo "Changes detected in foxtive, publishing..."
            cargo publish -p foxtive
          fi
          if [[ "${{ needs.detect-changes.outputs.changed_crates }}" == *"foxtive-macros"* ]]; then
            echo "Changes detected in foxtive-macros, publishing..."
            cargo publish -p foxtive-macros
          fi

  lint-code:
    name: Lint Codebase
    runs-on: ubuntu-latest
    needs: [detect-changes, test-code, release]
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Commit fmt changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(cargo-fmt): apply changes" || echo "No changes to commit"

      - name: Push fmt changes
        run: git push origin HEAD:${{ github.ref }}