name: Code QA & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test-code:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed crates
        id: detect-changes
        run: |
          # Find which crates were changed in this commit
          CHANGED_CRATES=$(git diff --name-only HEAD~1..HEAD | grep -E '^[^/]+/' | cut -d '/' -f 1 | sort | uniq)
          echo "Changed crates: $CHANGED_CRATES"
          echo "changed_crates=$CHANGED_CRATES" >> $GITHUB_ENV

      - name: Run Clippy on changed crates
        run: |
          if [[ "$changed_crates" == *"foxtive"* ]]; then
            cargo clippy --package foxtive --all-targets --all-features
          fi
          if [[ "$changed_crates" == *"foxtive-macros"* ]]; then
            cargo clippy --package foxtive-macros --all-targets --all-features
          fi

      - name: Run Tests on changed crates
        run: |
          if [[ "$changed_crates" == *"foxtive"* ]]; then
            cargo test --package foxtive --features=regex,crypto,base64,hmac,reqwest
          fi
          if [[ "$changed_crates" == *"foxtive-macros"* ]]; then
            cargo test --package foxtive-macros --features=database
          fi

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: test-code
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Detect changes in crates and release updated crates
        run: |
          if [[ "$changed_crates" == *"foxtive"* ]]; then
            echo "Changes detected in foxtive, publishing..."
            cargo publish -p foxtive
          fi
          if [[ "$changed_crates" == *"foxtive-macros"* ]]; then
            echo "Changes detected in foxtive-macros, publishing..."
            cargo publish -p foxtive-macros
          fi

  lint-code:
    name: Lint Codebase
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        if: github.event_name == 'push'
        run: cargo fmt --all

      - name: Commit fmt changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(cargo-fmt): apply changes" || echo "No changes to commit"

      - name: Push fmt changes
        if: github.event_name == 'push' && success()
        run: git push origin HEAD:${{ github.ref }}
